name: CI
on:
  - push
  - pull_request
jobs:
  phpunit:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
          coverage: xdebug2
      - run: composer config --no-plugins allow-plugins.infection/extension-installer true
      - run: composer update --optimize-autoloader
      - name: phpunit test
        env:
          XDEBUG_MODE: coverage
        run: composer test -- --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_SECRET}}
          fail_ci_if_error: true
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
      - run: composer config --no-plugins allow-plugins.infection/extension-installer true
      - run: composer update --optimize-autoloader
      - name: phpstan analyze
        run: composer analyze
  infection:
    name: Mutation test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
          coverage: xdebug2
      - run: composer config --no-plugins allow-plugins.infection/extension-installer true
      - run: composer update --optimize-autoloader
      - name: infection
        env:
          XDEBUG_MODE: coverage
        run: composer infection
      - uses: actions/upload-artifact@v1
        with:
          name: infection.log
          path: infection.log
      - uses: actions/upload-artifact@v1
        with:
          name: infection-summary.log
          path: infection-summary.log
      - uses: actions/upload-artifact@v1
        with:
          name: infection-per-mutator.md
          path: infection-per-mutator.md
